### ISSUE TITLE
Follow up with Dan about sec review process

### ISSUE THREAD

**Issue by dsmithpadilla** [mozilla/Relman-PostMortems#22]
Revamped download panel had to be [disabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1753096) during RC week due to a security issue reported by an external reporter

**Comment by rvandermeulen** [comment]
Discussed with Dan during the March 1 channel meeting. Dan is in the process of moving sec review status into Jira for better visibility, but at the moment it's just him doing them on a part-time basis due to limited resources. Also, the download panel did go through sec review but this specific problem wasn't something we were likely to catch that way.
